x-deploy: &deploy
  deploy:
    replicas: 1
    placement:
      constraints:
        - node.hostname == ${HOSTNAME}
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s

version: '3'
services:
  dripdrop-server:
    image: dripdrop/image
    container_name: dripdrop-server
    <<: *deploy
    command: [ "./scripts/server.sh" ]
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:5000/healthcheck"
        ]
      interval: 30s
    environment:
      ENV: ${ENV}

  dripdrop-worker:
    image: dripdrop/image
    <<: *deploy
    command: [ "./scripts/worker.sh" ]
    environment:
      ENV: ${ENV}
      REDIS_URL: ${REDIS_URL}

  dripdrop-postgres:
    image: postgres:14
    container_name: dripdrop-postgres
    <<: *deploy
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE}
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - type: volume
        source: postgres_volume
        target: /var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DATABASE}" ]
      interval: 30s

  dripdrop-redis:
    image: redis
    container_name: dripdrop-redis
    <<: *deploy
    volumes:
      - type: volume
        source: redis_volume
        target: /data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
