FROM python:3.10
RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get install -y ffmpeg && \
    curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt-get install -y nodejs
RUN pip install -U pip
RUN npm install -g npm
RUN mkdir -p /src
RUN mkdir -p /src/app
COPY ./requirements.txt /src/requirements.txt
COPY ./app/package.json /src/app/package.json
COPY ./app/package-lock.json /src/app/package-lock.json
WORKDIR /src
RUN pip install -r requirements.txt
RUN npm install -g