FROM python:3.10
RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get install -y ffmpeg
RUN mkdir -p /src
ADD . /src
WORKDIR /src
RUN pip install -r requirements.txt
RUN ECHO $REDIS_URL
ENTRYPOINT rq worker --with-scheduler $REDIS_URL