FROM python:3.10
RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get install -y ffmpeg && \
    curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt-get install -y nodejs
RUN pip install -r requirements.txt
RUN npm --prefix app install && NODE_ENV=production npm --prefix app run build
RUN mv app/build .