FROM python:3.10
RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get install -y ffmpeg
RUN mkdir -p /src
ADD . /src
WORKDIR /src
RUN pip install -r requirements.txt
RUN curl -L https://git.io/n-install | bash
RUN n lts
RUN npm --prefix app install && NODE_ENV=production npm --prefix app run build
RUN mv app/build .