FROM python:3.10
RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get install -y ffmpeg && \
    curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt-get install -y nodejs
RUN pip install -U pip
RUN pip install poetry
RUN npm install -g npm
RUN mkdir -p /src
COPY ./poetry.lock /src/poetry.
COPY ./pyproject.toml /src/pyproject.toml
WORKDIR /src
RUN poetry install