FROM python:3.10
RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get install -y ffmpeg
RUN pip install -U pip
RUN pip install poetry
RUN mkdir -p /src
COPY . /src
WORKDIR /src
RUN poetry export -f requirements.txt --output requirements.txt
RUN pip install -r requirements.txt
RUN chmod +x ./scripts/web.sh