FROM python:3.10
RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get install -y ffmpeg
RUN mkdir -p /src
ADD ./requirements.txt /src/requirements.txt
WORKDIR /src
RUN pip install -r requirements.txt