FROM python:3.10
RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get install -y ffmpeg
RUN pip install -U pip
RUN pip install poetry
RUN mkdir -p /src
ADD ./poetry.lock /src/poetry.
ADD ./pyproject.toml /src/pyproject.toml
WORKDIR /src
RUN poetry install