FROM python:3.10
RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get install -y ffmpeg && \
    curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt-get install -y nodejs
RUN pip install -U pip
RUN npm install -g npm
RUN mkdir -p /src
COPY . /src
WORKDIR /src
RUN pip install -r requirements.txt
RUN npm --prefix app install
RUN NODE_ENV=$ENV npm --prefix app run build && mv app/build .
RUN chmod +x ./scripts/web.sh