"""add info columns

Revision ID: 155d7dc7e2e5
Revises: e83f5707bf96
Create Date: 2021-10-22 00:05:37.577848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155d7dc7e2e5'
down_revision = 'e83f5707bf96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music_jobs', sa.Column('youtube_url', sa.String(), nullable=True))
    op.add_column('music_jobs', sa.Column('filename', sa.String(), nullable=True))
    op.add_column('music_jobs', sa.Column('artwork_url', sa.String(), nullable=True))
    op.add_column('music_jobs', sa.Column('title', sa.String(), nullable=True))
    op.add_column('music_jobs', sa.Column('artist', sa.String(), nullable=True))
    op.add_column('music_jobs', sa.Column('album', sa.String(), nullable=True))
    op.add_column('music_jobs', sa.Column('grouping', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music_jobs', 'grouping')
    op.drop_column('music_jobs', 'album')
    op.drop_column('music_jobs', 'artist')
    op.drop_column('music_jobs', 'title')
    op.drop_column('music_jobs', 'artwork_url')
    op.drop_column('music_jobs', 'filename')
    op.drop_column('music_jobs', 'youtube_url')
    # ### end Alembic commands ###
