"""create jobs table

Revision ID: e83f5707bf96
Revises:
Create Date: 2021-10-19 20:47:02.384032

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e83f5707bf96"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "music_jobs",
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("job_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("music_jobs")
    # ### end Alembic commands ###
