"""add default time for last updated on yt channels

Revision ID: 9f43a1bd1b03
Revises: 2426dbe78bbd
Create Date: 2021-12-31 03:34:52.639259

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9f43a1bd1b03"
down_revision = "2426dbe78bbd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("youtube_channels", "last_updated", server_default=sa.text("NOW()"))
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("youtube_channels", "last_updated", server_default=None)
    pass
    # ### end Alembic commands ###
