"""add user relation to jobs

Revision ID: 86551b773c09
Revises: cfbcd0505d90
Create Date: 2021-11-08 19:07:48.710355

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "86551b773c09"
down_revision = "cfbcd0505d90"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("music_jobs", sa.Column("username", sa.String(), nullable=True))
    op.create_foreign_key(None, "music_jobs", "users", ["username"], ["username"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "music_jobs", type_="foreignkey")
    op.drop_column("music_jobs", "username")
    # ### end Alembic commands ###
