"""add additional info to table

Revision ID: 7e43a80afadb
Revises: e83f5707bf96
Create Date: 2021-10-24 19:37:46.199761

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7e43a80afadb"
down_revision = "e83f5707bf96"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("music_jobs", sa.Column("jobID", sa.String(), nullable=False))
    op.add_column("music_jobs", sa.Column("filename", sa.String(), nullable=True))
    op.add_column("music_jobs", sa.Column("youtubeURL", sa.String(), nullable=True))
    op.add_column("music_jobs", sa.Column("artworkURL", sa.String(), nullable=True))
    op.add_column("music_jobs", sa.Column("title", sa.String(), nullable=True))
    op.add_column("music_jobs", sa.Column("artist", sa.String(), nullable=True))
    op.add_column("music_jobs", sa.Column("album", sa.String(), nullable=True))
    op.add_column("music_jobs", sa.Column("grouping", sa.String(), nullable=True))
    op.alter_column(
        "music_jobs", "completed", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.drop_column("music_jobs", "job_id")
    op.create_primary_key("pk_music_jobs", "music_jobs", ["jobID"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "music_jobs",
        sa.Column("job_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "music_jobs", "completed", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.drop_column("music_jobs", "grouping")
    op.drop_column("music_jobs", "album")
    op.drop_column("music_jobs", "artist")
    op.drop_column("music_jobs", "title")
    op.drop_column("music_jobs", "artworkURL")
    op.drop_column("music_jobs", "youtubeURL")
    op.drop_column("music_jobs", "filename")
    op.drop_column("music_jobs", "jobID")
    op.create_primary_key("pk_music_jobs", "music_jobs", ["job_id"])
    # ### end Alembic commands ###
