"""no need for websocket tokens

Revision ID: cfbcd0505d90
Revises: 0bee042466a3
Create Date: 2021-11-06 04:04:21.120572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cfbcd0505d90"
down_revision = "0bee042466a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("websocket_tokens")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "websocket_tokens",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["username"], ["users.username"], name="websocket_tokens_username_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="websocket_tokens_pkey"),
    )
    # ### end Alembic commands ###
