"""create session and user tables

Revision ID: 8dea6b4253bf
Revises: ca200e798e83
Create Date: 2021-11-04 19:48:08.472230

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8dea6b4253bf"
down_revision = "ca200e798e83"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("admin", sa.Boolean(), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column(
            "createdAt",
            postgresql.TIMESTAMP(),
            server_default=sa.text("NOW()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("username"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["username"], ["users.username"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column("music_jobs", "title", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("music_jobs", "artist", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("music_jobs", "album", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "music_jobs", "completed", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column("music_jobs", "failed", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("music_jobs", "failed", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "music_jobs", "completed", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column("music_jobs", "album", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("music_jobs", "artist", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("music_jobs", "title", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_table("sessions")
    op.drop_table("users")
    # ### end Alembic commands ###
