"""update foreign key relations

Revision ID: 7c36d6ca112e
Revises: 86551b773c09
Create Date: 2021-11-08 19:09:12.593356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7c36d6ca112e"
down_revision = "86551b773c09"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "music_jobs", "username", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("sessions", "username", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("sessions", "username", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("music_jobs", "username", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
