"""add published at field for subscriptions

Revision ID: 6af1f00cd38b
Revises: b78f50579748
Create Date: 2022-01-03 18:39:33.226741

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6af1f00cd38b"
down_revision = "b78f50579748"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "youtube_subscriptions",
        sa.Column("published_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("youtube_subscriptions", "published_at")
    # ### end Alembic commands ###
