"""move category id to videos

Revision ID: 411683133de6
Revises: 049d448a0f8d
Create Date: 2022-01-01 01:24:09.811613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "411683133de6"
down_revision = "049d448a0f8d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "youtube_videos", sa.Column("category_id", sa.Integer(), nullable=True)
    )
    op.execute(
        "UPDATE youtube_videos SET category_id = (SELECT category_id from youtube_video_category \
            WHERE video_id = youtube_videos.id) WHERE TRUE;"
    )
    op.alter_column("youtube_videos", "category_id", nullable=False)
    op.drop_table("youtube_video_category")
    op.create_foreign_key(
        None,
        "youtube_videos",
        "youtube_video_categories",
        ["category_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "youtube_video_category",
        sa.Column("video_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("category_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["youtube_video_categories.id"],
            name="youtube_video_category_category_id_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["youtube_videos.id"],
            name="youtube_video_category_video_id_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
    )
    op.execute(
        "INSERT INTO youtube_video_category (video_id, category_id) \
            SELECT id as video_id, category_id FROM youtube_videos"
    )
    op.drop_constraint(
        "youtube_videos_category_id_fkey", "youtube_videos", type_="foreignkey"
    )
    op.drop_column("youtube_videos", "category_id")

    # ### end Alembic commands ###
