"""remove youtube jobs, add field to indicate subscriptions are being updated

Revision ID: 6f73ab459616
Revises: 6af1f00cd38b
Create Date: 2022-01-12 22:27:18.319023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6f73ab459616"
down_revision = "6af1f00cd38b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("youtube_jobs")
    op.add_column(
        "google_accounts",
        sa.Column(
            "subscriptions_loading", sa.Boolean(), nullable=False, server_default="0"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("google_accounts", "subscriptions_loading")
    op.create_table(
        "youtube_jobs",
        sa.Column("job_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("completed", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("failed", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["email"],
            ["google_accounts.email"],
            name="youtube_jobs_email_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("job_id", name="youtube_jobs_pkey"),
    )
    # ### end Alembic commands ###
