"""add deleted at field for jobs

Revision ID: e53040d5319c
Revises: 29441cf1e4ae
Create Date: 2022-11-14 07:19:03.379199

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e53040d5319c"
down_revision = "29441cf1e4ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "music_jobs",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("music_jobs", "deleted_at")
    # ### end Alembic commands ###
