"""add youtube video watches

Revision ID: c13ce1d4196d
Revises: 113fddd62ffa
Create Date: 2022-05-24 23:27:43.860155

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c13ce1d4196d"
down_revision = "113fddd62ffa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "youtube_video_watches",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("video_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["email"],
            ["google_accounts.email"],
            name="youtube_video_watches_email_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["youtube_videos.id"],
            name="youtube_video_watches_video_id_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("email", "video_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("youtube_video_watches")
    # ### end Alembic commands ###
