"""add download url to music jobs

Revision ID: 876555a5ff33
Revises: c0ec00254dca
Create Date: 2022-08-08 02:35:24.026220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "876555a5ff33"
down_revision = "c0ec00254dca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("music_jobs", sa.Column("download_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("music_jobs", "download_url")
    # ### end Alembic commands ###
