"""remove sessions

Revision ID: 29441cf1e4ae
Revises: 876555a5ff33
Create Date: 2022-11-10 06:57:22.794979

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "29441cf1e4ae"
down_revision = "876555a5ff33"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sessions")
    op.create_unique_constraint(None, "google_accounts", ["user_email"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "google_accounts", type_="unique")
    op.create_table(
        "sessions",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_email"],
            ["users.email"],
            name="sessions_user_email_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="sessions_pkey"),
    )
    # ### end Alembic commands ###
