"""remove playlist ids, last updated from channels

Revision ID: 9513f3cf6369
Revises: 86423a581cf8
Create Date: 2023-02-20 07:17:09.326454

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "9513f3cf6369"
down_revision = "86423a581cf8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("youtube_channels", "upload_playlist_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "youtube_channels",
        sa.Column(
            "upload_playlist_id", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
