"""add updating column to youtube channels

Revision ID: 5fd00d60a7ba
Revises: a653fb869f40
Create Date: 2023-04-11 05:42:39.904350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5fd00d60a7ba"
down_revision = "a653fb869f40"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "youtube_channels", sa.Column("updating", sa.Boolean(), nullable=True)
    )
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE youtube_channels SET updating = FALSE"))
    op.alter_column("youtube_channels", "updating", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("youtube_channels", "updating")
    # ### end Alembic commands ###
