"""add youtube user channels table

Revision ID: 6ea1bfc0c7b5
Revises: a6924ec169fd
Create Date: 2023-03-04 22:05:59.155578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6ea1bfc0c7b5"
down_revision = "a6924ec169fd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "youtube_user_channels",
        sa.Column("channel_id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("last_updated", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["email"],
            ["users.email"],
            name="youtube_user_channels_email_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("channel_id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("youtube_user_channels")
    # ### end Alembic commands ###
