"""add deleted at to youtube subscriptions

Revision ID: 58d29fd76d19
Revises: 5e8fad39116c
Create Date: 2023-03-05 22:23:22.158905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "58d29fd76d19"
down_revision = "5e8fad39116c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "youtube_subscriptions",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("youtube_subscriptions", "deleted_at")
    # ### end Alembic commands ###
