"""add youtube new subscriptions table

Revision ID: d05f36087735
Revises: 9513f3cf6369
Create Date: 2023-02-25 22:03:08.664903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d05f36087735"
down_revision = "9513f3cf6369"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "youtube_new_subscriptions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("last_updated", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["email"],
            ["google_accounts.email"],
            name="youtube_new_subscriptions_email_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("youtube_new_subscriptions")
    # ### end Alembic commands ###
