"""change youtube url field to video_url

Revision ID: 86423a581cf8
Revises: 2f49b5e6155e
Create Date: 2023-02-18 22:32:11.099077

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "86423a581cf8"
down_revision = "2f49b5e6155e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("music_jobs", sa.Column("video_url", sa.String(), nullable=True))
    op.drop_column("music_jobs", "youtube_url")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "music_jobs",
        sa.Column("youtube_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("music_jobs", "video_url")
    # ### end Alembic commands ###
