"""update youtube video category ids

Revision ID: a653fb869f40
Revises: 346ac6c2eb22
Create Date: 2023-03-25 20:06:24.478036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a653fb869f40"
down_revision = "346ac6c2eb22"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    results = connection.execute(
        sa.text("SELECT max(youtube_video_categories.id) FROM youtube_video_categories")
    )
    restart = results.scalar()
    op.execute(f"ALTER SEQUENCE youtube_video_categories_id_seq RESTART WITH {restart}")
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
