"""remove subscription ids and published columns

Revision ID: f8f9d34f5126
Revises: 224e64563fab
Create Date: 2023-03-22 04:24:07.978155

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f8f9d34f5126"
down_revision = "224e64563fab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("youtube_subscriptions", "id")
    op.drop_column("youtube_subscriptions", "published_at")
    op.create_primary_key(
        "youtube_subscriptions_pkey", "youtube_subscriptions", ["channel_id", "email"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("youtube_subscriptions_pkey")
    op.add_column(
        "youtube_subscriptions",
        sa.Column(
            "published_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "youtube_subscriptions",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_primary_key("youtube_subscriptions_pkey", "youtube_subscriptions", ["id"])
    # ### end Alembic commands ###
