"""update youtube new subscriptions table to match youtube subscriptions

Revision ID: f3f816421196
Revises: f8f9d34f5126
Create Date: 2023-03-23 03:36:40.126721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f3f816421196"
down_revision = "f8f9d34f5126"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "youtube_new_subscriptions",
        sa.Column("channel_id", sa.String(), nullable=False),
    )
    op.drop_column("youtube_new_subscriptions", "id")
    op.create_primary_key(
        "youtube_new_subscriptions_pk",
        "youtube_new_subscriptions",
        ["channel_id", "email"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "youtube_new_subscriptions",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("youtube_new_subscriptions", "channel_id")
    op.create_primary_key(
        "youtube_new_subscriptions_pk", "youtube_new_subscriptions", ["id"]
    )
    # ### end Alembic commands ###
