"""add proxies

Revision ID: 346ac6c2eb22
Revises: f3f816421196
Create Date: 2023-03-24 02:56:13.239327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "346ac6c2eb22"
down_revision = "f3f816421196"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proxies",
        sa.Column("ip_address", sa.String(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("last_used", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("ip_address"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("proxies")
    # ### end Alembic commands ###
