"""add verification to users

Revision ID: 91ed3c56aa5e
Revises: 5fd00d60a7ba
Create Date: 2023-05-18 17:25:21.533010

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "91ed3c56aa5e"
down_revision = "5fd00d60a7ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("verified", sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET verified = 'true'")
    op.alter_column("users", "verified", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "verified")
    # ### end Alembic commands ###
