"""add description to youtube videos

Revision ID: 224e64563fab
Revises: df6a1da1693c
Create Date: 2023-03-13 06:55:09.470812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "224e64563fab"
down_revision = "df6a1da1693c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("youtube_videos", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("youtube_videos", "description")
    # ### end Alembic commands ###
