"""change last updated column name to modified_at

Revision ID: 5e8fad39116c
Revises: 6ea1bfc0c7b5
Create Date: 2023-03-05 02:43:55.554442

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "5e8fad39116c"
down_revision = "6ea1bfc0c7b5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE music_jobs RENAME COLUMN last_updated TO modified_at")
    op.execute("ALTER TABLE users RENAME COLUMN last_updated TO modified_at")
    op.execute("ALTER TABLE youtube_channels RENAME COLUMN last_updated TO modified_at")
    op.execute(
        "ALTER TABLE youtube_new_subscriptions RENAME COLUMN last_updated TO modified_at"
    )
    op.execute(
        "ALTER TABLE youtube_subscriptions RENAME COLUMN last_updated TO modified_at"
    )
    op.execute(
        "ALTER TABLE youtube_user_channels RENAME COLUMN last_updated TO modified_at"
    )
    op.execute(
        "ALTER TABLE youtube_video_categories RENAME COLUMN last_updated TO modified_at"
    )
    op.execute(
        "ALTER TABLE youtube_video_likes RENAME COLUMN last_updated TO modified_at"
    )
    op.execute(
        "ALTER TABLE youtube_video_queues RENAME COLUMN last_updated TO modified_at"
    )
    op.execute(
        "ALTER TABLE youtube_video_watches RENAME COLUMN last_updated TO modified_at"
    )
    op.execute("ALTER TABLE youtube_videos RENAME COLUMN last_updated TO modified_at")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE music_jobs RENAME COLUMN modified_at TO last_updated")
    op.execute("ALTER TABLE users RENAME COLUMN modified_at TO last_updated")
    op.execute("ALTER TABLE youtube_channels RENAME COLUMN modified_at TO last_updated")
    op.execute(
        "ALTER TABLE youtube_new_subscriptions RENAME COLUMN modified_at TO last_updated"
    )
    op.execute(
        "ALTER TABLE youtube_subscriptions RENAME COLUMN modified_at TO last_updated"
    )
    op.execute(
        "ALTER TABLE youtube_user_channels RENAME COLUMN modified_at TO last_updated"
    )
    op.execute(
        "ALTER TABLE youtube_video_categories RENAME COLUMN modified_at TO last_updated"
    )
    op.execute(
        "ALTER TABLE youtube_video_likes RENAME COLUMN modified_at TO last_updated"
    )
    op.execute(
        "ALTER TABLE youtube_video_queues RENAME COLUMN modified_at TO last_updated"
    )
    op.execute(
        "ALTER TABLE youtube_video_watches RENAME COLUMN modified_at TO last_updated"
    )
    op.execute("ALTER TABLE youtube_videos RENAME COLUMN modified_at TO last_updated")
    # ### end Alembic commands ###
