"""use created at_and last up_ated on all models, add last_videos_updated to youtube channels

Revision ID: 2f49b5e6155e
Revises: 7aa0e953eff8
Create Date: 2023-01-25 19:53:17.378632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2f49b5e6155e"
down_revision = "7aa0e953eff8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("google_accounts", "subscriptions_loading")
    op.add_column(
        "music_jobs", sa.Column("last_updated", sa.TIMESTAMP(timezone=True), nullable=False)
    )
    op.add_column("users", sa.Column("last_updated", sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column(
        "youtube_channels",
        sa.Column("last_videos_updated", sa.TIMESTAMP(timezone=True), nullable=False),
    )
    op.add_column(
        "youtube_subscriptions",
        sa.Column("last_updated", sa.TIMESTAMP(timezone=True), nullable=False),
    )
    op.add_column(
        "youtube_video_categories",
        sa.Column("last_updated", sa.TIMESTAMP(timezone=True), nullable=False),
    )
    op.add_column(
        "youtube_video_likes",
        sa.Column("last_updated", sa.TIMESTAMP(timezone=True), nullable=False),
    )
    op.add_column(
        "youtube_video_queues",
        sa.Column("last_updated", sa.TIMESTAMP(timezone=True), nullable=False),
    )
    op.add_column(
        "youtube_video_watches",
        sa.Column("last_updated", sa.TIMESTAMP(timezone=True), nullable=False),
    )
    op.add_column(
        "youtube_videos", sa.Column("last_updated", sa.TIMESTAMP(timezone=True), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("youtube_videos", "last_updated")
    op.drop_column("youtube_video_watches", "last_updated")
    op.drop_column("youtube_video_queues", "last_updated")
    op.drop_column("youtube_video_likes", "last_updated")
    op.drop_column("youtube_video_categories", "last_updated")
    op.drop_column("youtube_subscriptions", "last_updated")
    op.drop_column("youtube_channels", "last_videos_updated")
    op.drop_column("users", "last_updated")
    op.drop_column("music_jobs", "last_updated")
    op.add_column(
        "google_accounts",
        sa.Column(
            "subscriptions_loading",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
