"""add cascade and delete effects to foreign keys

Revision ID: 3a41f09260a6
Revises: 68a57d37fad0
Create Date: 2021-12-22 01:51:11.342969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a41f09260a6'
down_revision = '68a57d37fad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('google_accounts_username_fkey',
                       'google_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'google_accounts', 'users', ['user_email'], [
                          'email'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('music_jobs_username_fkey',
                       'music_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'music_jobs', 'users', ['user_email'], [
                          'email'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('sessions_username_fkey',
                       'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_email'], [
                          'email'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('youtube_jobs_email_fkey',
                       'youtube_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'youtube_jobs', 'google_accounts', ['email'], [
                          'email'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'youtube_jobs', type_='foreignkey')
    op.create_foreign_key('youtube_jobs_email_fkey',
                          'youtube_jobs', 'google_accounts', ['email'], ['email'])
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_user_email_fkey',
                          'sessions', 'users', ['user_email'], ['email'])
    op.drop_constraint(None, 'music_jobs', type_='foreignkey')
    op.create_foreign_key('music_jobs_user_email_fkey',
                          'music_jobs', 'users', ['user_email'], ['email'])
    op.drop_constraint(None, 'google_accounts', type_='foreignkey')
    op.create_foreign_key('google_accounts_user_email_fkey',
                          'google_accounts', 'users', ['user_email'], ['email'])
    # ### end Alembic commands ###
