"""add more filename fields to music jobs

Revision ID: 7aa0e953eff8
Revises: e53040d5319c
Create Date: 2023-01-08 20:08:19.353319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7aa0e953eff8"
down_revision = "e53040d5319c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "music_jobs", sa.Column("artwork_filename", sa.String(), nullable=True)
    )
    op.add_column(
        "music_jobs", sa.Column("original_filename", sa.String(), nullable=True)
    )
    op.add_column("music_jobs", sa.Column("filename_url", sa.String(), nullable=True))
    op.add_column(
        "music_jobs", sa.Column("download_filename", sa.String(), nullable=True)
    )
    op.drop_column("music_jobs", "filename")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "music_jobs",
        sa.Column("filename", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("music_jobs", "download_filename")
    op.drop_column("music_jobs", "filename_url")
    op.drop_column("music_jobs", "original_filename")
    op.drop_column("music_jobs", "artwork_filename")
    # ### end Alembic commands ###
